### ISSUE TITLE
Error from run_model, before model is run by Stan

### ISSUE THREAD

**Issue by tmeeha** [bbsBayes/bbsBayes2#81] opened 2024-09-16 16:04 UTC
Hello Adam and Brandon,

Wondering if you know what this error is about. It comes from run_model. Just FYI, this is my first go with bbsBayes2. I think (?) it is setup correctly. I followed you directions about running it on linux.

Thanks, 
Tim

> s <- stratify(by = "bbs_cws", species = "American Dipper") 
_Using 'bbs_cws' (standard) stratification Loading BBS data... 
Filtering to species American Dipper (7010) 
Stratifying data...   
Combining BCR 7 and NS and PEI...   
Renaming routes..._ 
> p <- prepare_data(s) 
> map <- load_map("bbs_cws") 
> sp <- prepare_spatial(p, map) 
_Preparing spatial data... 
Identifying neighbours (non-Voronoi method)... 
Formating neighbourhood matrices... 
Plotting neighbourhood matrices..._ 
> print(sp$spatial_data$map) 
> pm <- prepare_model(sp, model = "first_diff", model_variant="spatial", use_pois=FALSE) 
> m <- run_model(md, iter_sampling = 100, iter_warmup = 500, chains = 2) 
_Model executable is up to date! 
Error in strsplit(path_metadata, " ", fixed = TRUE)[[1]] :    
subscript out of bounds_

**Comment by AdamCSmithCWS** [comment] 2024-09-17 17:22
Thanks @tmeeha . 

I ran the following code and it's working at my end. Is it possible that in the last line of code, you've used an object "md" that happened to exist in your working environment, when you intended to use the object "pm"?

```{r}
s <- stratify(by = "bbs_cws", species = "American Dipper")
p <- prepare_data(s)
map <- load_map("bbs_cws")
sp <- prepare_spatial(p, map)
print(sp$spatial_data$map)
pm <- prepare_model(sp, model = "first_diff", model_variant="spatial", use_pois=FALSE)
## note pm object in next line.
m <- run_model(pm, iter_sampling = 100, iter_warmup = 500, chains = 2)
```

**Comment by tmeeha** [comment] 2024-09-17 17:44
Hmm. Still getting the error in a clean environment.

`m <- run_model(pm, iter_sampling = 100, iter_warmup = 500, chains = 2)`
_Model executable is up to date!
Error in strsplit(path_metadata, " ", fixed = TRUE)[[1]] : subscript out of bounds_

I wonder if I messed up the WSL install. Here is a check on that.

`cmdstanr::check_cmdstan_toolchain()`
_The C++ toolchain required for CmdStan is setup properly!_

**Comment by tmeeha** [comment] 2024-09-17 17:52
Yup. I just went to this page --  https://mc-stan.org/cmdstanr/articles/cmdstanr.html -- to test my stan setup and everything works with the cmdstanr examples. 

R version 4.4.1 (2024-06-14 ucrt) -- "Race for Your Life"
Copyright (C) 2024 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64

**Comment by AdamCSmithCWS** [comment] 2024-09-18 15:23
With a bit more exploration, I see you're correct that the error is coming from the cmdstanr package, within one of its utility functions that checks the wsl cmdstan path.  
https://github.com/stan-dev/cmdstanr/blob/master/R/path.R
https://github.com/stan-dev/cmdstanr/blob/master/R/utils.R

I haven't been able to reproduce it yet, but I'll keep working on it.

**Comment by AdamCSmithCWS** [comment] 2024-09-19 13:44
One thought, can you try this workaround?
```{r}
library(cmdstanr)
library(bbsBayes2)

s <- stratify(by = "bbs_cws", species = "American Dipper")
p <- prepare_data(s)
map <- load_map("bbs_cws")
sp <- prepare_spatial(p, map)
print(sp$spatial_data$map)
pm <- prepare_model(sp, model = "first_diff", model_variant="spatial", use_pois=FALSE)

model_data <- pm$model_data
model_data[["test"]] <- 1
model_data[["train"]] <- as.integer(1:model_data[["n_counts"]])
model_data[["n_test"]] <- 1
model_data[["n_train"]] <- model_data[["n_counts"]]
model_data[["calc_CV"]] <- 0

copy_model_file(model = "first_diff", model_variant="spatial",getwd())

model <- cmdstanr::cmdstan_model("first_diff_spatial_bbs_CV_COPY.stan")

model_fit <- model$sample(data = model_data,
  chains = 2,
  iter_sampling = 100,
  iter_warmup = 500)


```

**Comment by tmeeha** [comment] 2024-09-19 20:50
I might have found the problem. When my working directory lives on BOX (the file sharing cloud software), then cmdstanr::cmdstan_model() can't find the Stan file, even when I give it the full path. When the working directory is local, it can. So I can fix this on my end by not using a BOX folder as my working directory. Sorry for the wild goose chase!

**Comment by AdamCSmithCWS** [comment] 2024-09-20 15:27
I'm going to close this issue, but thanks for bringing this up. Working with Stan "at-scale" (large datasets, many datasets, many models running in parallel, complex network structures, etc.) is often tricky.

**Closed by AdamCSmithCWS** 2024-09-20 15:27 UTC
